### ISSUE TITLE
pychart down

### ISSUE THREAD

**Issue by schout-it** [anybox/anybox.recipe.odoo#102]
The anybox recipe 1.9 still has a dependencie on PyChart in the server.py
As gna.org is down and no mirror for it has popped up, this will break the install.

I can't find any mention of pychart in the requirement in v8.0 so I think it can be removed (as is done in later versions)

**Comment by petrus-v** [comment]
Hi,

Thanks for reporting this issue. PyChart is now available [on pypi](https://pypi.python.org/pypi/PyChart/1.39) so it shouldn't be a matter. But indeed if PyChart is not need since Odoo v8 it's good idea to remove it. Feel free to create a PR about that against master branch.

Regards

**Comment by schout-it** [comment]
Seems in master it's already deleted, so an upgrade to master should be enough
