### ISSUE TITLE
StefanRijnhart  As Maintainer of anybox.recipe.odoo

### ISSUE THREAD

**Issue by lmignon** [anybox/anybox.recipe.odoo#111]
Hi,

I want to propose @StefanRijnhart as maintainer of anybox.recipe.odoo. @StefanRijnhart actively supports the development of this recipe for a long time.

cc @petrus-v @gracinet 

lmi

**Comment by petrus-v** [comment]
👍 

@StefanRijnhart let me know if you want so! and I'll add you write access.

@gurneyalex If I rememeber properly during a code sprint (was at Pau I think during PyConFR 2015) you have started with @gracinet  to move this buildout recipe under OCA umbrella, what's the state of that move?

**Comment by StefanRijnhart** [comment]
Great, thanks!

**Comment by petrus-v** [comment]
@StefanRijnhart 

You should have receive a nonfiction to become Admin on those repos ``anybox.recipe.odoo`` and ``anybox.recipe.openerp``!

Thanks for your help to spend time here!
