### ISSUE TITLE
UnboundLocalError: local variable 'exc' referenced before assignment

### ISSUE THREAD

**Issue by kossovo** [anybox/anybox.recipe.odoo#125]
Try with Python 3.6 and Odoo 13.0

```bash
anybox.recipe.odoo/anybox/recipe/odoo/base.py", line 606, in install_requirements
    exc.__class__.__module__, exc.__class__.__name__, exc)
UnboundLocalError: local variable 'exc' referenced before assignment
```

**Comment by StefanRijnhart** [comment]
Indeed @kossovo, in the case of a missing or incorrect requirement this packages attempts to produce an informative error message but fails to do so, leading to the error that you encountered. I have submitted a fix. Thanks for reporting!

**Comment by StefanRijnhart** [comment]
Closing as there is a PR
