### ISSUE TITLE
Upgrade using folder instead of only one big file

### ISSUE THREAD

**Issue by sebastienbeau** [anybox/anybox.recipe.odoo#35]
Hi,
First of all thanks a lot for the buildout recipe!

I would like to propose an improvement for the management of upgrade script.
For now the upgrade script is only only one file and can increase quickly in the time. I would prefers to use by default a folder and one script per version.

To be more explicite I want only one upgrade folder with all of my script and this look like something like that : 
- upgrade
    - 1.0.0.py
    - 1.1.0.py
    - 1.2.0.py
    - 2.0.0.py

Script should be played in the right order and after each execution of the script the database is commited

I start to do a prototype that look something like that : https://gist.github.com/sebastienbeau/77ca66f2e87cca2c45ad

I would like to know if you are interesteed by including this feature by default in the recipe?

Thanks

**Comment by bwrsandman** [comment]
I don't think that would be very practical...

The issue would be that to upgrade to 1.1.0 the code of the addons needs to be set at 1.1.0, in which case the 1.2.0.py code would not work if there is a significant difference such as field renames.

**Comment by ccomb** [comment]
I'm not sure it's a good idea to enforce an execution logic, it may not fit with everyone's need. You may write this numbered execution logic directly in the upgrade.py module if you need. BTW have you tried to import a 1.0.0.py module from the upgrade.py ? Does it work?
Curious about @gracinet 's opinion.

**Comment by sebastienbeau** [comment]
I am closing the issue, we just modify our upgrade.py to import run the needed script in upgrade folder. not need to customise the recipe
