### ISSUE TITLE
Revert before update also

### ISSUE THREAD

**Issue by agb80** [anybox/anybox.recipe.odoo#46]
Will be great if we can add an option to vcs-revert so we can revert the merges before update repositories. 

Currently this is the user case, just pasting relevant parts from my buildout recipe:

```
[buildout]
parts = openerp
versions = versions
find-links = http://download.gna.org/pychart/

[openerp]
recipe = anybox.recipe.openerp[bzr]:server
version = git https://github.com/OCA/OCB server master

addons = git http://gitlab.openpyme.mx/l10n_mx/facturacion.git parts/l10n_mx master
         git https://github.com/OCA/account-financial-reporting.git parts/account_financial_reporting 7.0
         git http://gitlab.openpyme.mx/l10n_mx/l10n_mx.git parts/l10n_mx master group=l10n_mx
         git https://github.com/OCA/connector.git parts/connector 7.0
         git https://github.com/OpenPymeMx/connector-drupal.git parts/drupal-connector nsgt
         local parts/server/addons 

merges = 
         git http://gitlab.openpyme.mx/l10n_mx/facturacion.git parts/l10n_mx signals
         git http://gitlab.openpyme.mx/l10n_mx/facturacion.git parts/l10n_mx workflow
         
vcs-revert = on-merge
```

As you can see there is a repo named facturacion where we are merging two WIP branches. First time we run the buildout.py there is no problem, everything works ok, but if we commit a bug fix to master branch and then we try to run the buildout.py again we got an error because facturacion repo no longer can be fast forwarded.

I know for sure that there is no conflicts on the commited bug fix and the two WIP branches, in fact if manually reset git branch to a prev commit and re run the buildout.py everything works as expected.

**Comment by sbidoul** [comment]
@agb80 have you tried the vsc-clear-retry option?

**Comment by agb80** [comment]
@sbidoul do you mean this one: http://pythonhosted.org/anybox.recipe.odoo/configuration.html#clean? I'm going to try and let you know what happen!

**Comment by sbidoul** [comment]
@agb80 I meant this one: http://docs.anybox.fr/anybox.recipe.odoo/current/configuration.html#vcs-clear-retry

**Comment by agb80** [comment]
Interesting, the documentation is different from the one I was using, maybe an update for readme is needed.

That was exactly the option I needed, thank you very much @sbidoul

**Comment by lepistone** [comment]
Hi! I followed your same reasoning for the same situation and only now I found this issue.

It looks like the `vcs-revert` option should always be used with `vcs-clear-retry`. The problem is the one described by @agb80: when upstream advances, the recipe tries to fast-forward before `vcs-retry` has had the time to reset to `origin/8.0`. This is somewhat less than ideal, at least since `vcs-retry` is documented as a brittle thing.

What do you think about that?

Thanks!
