### ISSUE TITLE
Coverage result provided by coveralls.io is wrong

### ISSUE THREAD

**Issue by lmignon** [anybox/anybox.recipe.odoo#52]
result by coveralls.io: 40%
result in the build output: 86%

**Comment by bwrsandman** [comment]
Even using `coveralls debug`, the result is different... 
https://travis-ci.org/anybox/anybox.recipe.odoo/builds/72876206#L3932

**Comment by jssuzanne** [comment]
Hi, I haven't write it yet but for another framework a i had the same case,
with a nose plugging we can load odoo after coverage and get the good
coverage. I don't know if the plugging must be with the recipe or be in
other egg

2015-07-27 19:50 GMT+02:00 Sandy <notifications@github.com>:

> Even using coveralls debug, the result is different...
> https://travis-ci.org/anybox/anybox.recipe.odoo/builds/72876206#L3932
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anybox/anybox.recipe.odoo/issues/52#issuecomment-125285800>
> .
>



-- 

Jean-Sébastien SUZANNE

jssuzanne@anybox.fr

**Comment by lmignon** [comment]
fixed by #55

**Comment by petrus-v** [comment]
@jssuzanne,

Yeah it could be great to port your nose plugging to anybox.recipe.odoo!

If it's nose plugging that can works without this recipe, I'll suggest to create another package.
