### ISSUE TITLE
Building documentation

### ISSUE THREAD

**Issue by petrus-v** [anybox/anybox.recipe.odoo#56]
Hi,

#50 failed building the documentation: https://buildbot.anybox.fr/builders/anybox.recipe.odoo/builds/59/steps/sphinx/logs/stdio

I suggest to build documentation on travis as well, to let developer know when create a PR if it will pass or failed on buildbot.

I hope the [html setting](https://github.com/anybox/anybox.recipe.odoo/pull/50/files#diff-684a0ceb2878d48b19612ca360e277efR97) isn't environment dependent ?

**Comment by petrus-v** [comment]
On that build, the buildslave was running Sphinx v1.3b2, as long sphinx version is now 1.3.1 which suggest to use classic theme, It would be better to upgrade Anybox buildslaves with lastest sphinx version.

I'll create PR to build doc using sphinx to let developers knows if their rst documentation failed at PR time, not at merge time and upgrade buildslaves.

**Comment by petrus-v** [comment]
I cleanup buildslaves: https://buildbot.anybox.fr/builders/anybox.recipe.odoo/builds/61

doc uploaded: http://docs.anybox.fr/anybox.recipe.odoo/current

**Comment by petrus-v** [comment]
I'll need to spend more time to investigate what's wrong.

For sure:
* A new release of babel was done yesterday (v2.0)[https://pypi.python.org/pypi/Babel/2.0].
* In unit test recipe is playing with a (fake babel)[https://github.com/anybox/anybox.recipe.odoo/tree/master/anybox/recipe/odoo/tests/fake_babel].
* Sphinx require babel.

**Comment by petrus-v** [comment]
Building doc with travis will be done by #59, also related as theme was changed to the default *classic* sphinx theme is to use responsive design #60.

**Comment by lmignon** [comment]
Resolved by merging #59 at a5cbb00f0d244c9aa7c1612fd968e31367a7a5cd
