### ISSUE TITLE
Odoo 7.0: Couldn't find a distribution for 'PIL'

### ISSUE THREAD

**Issue by ssaid** [anybox/anybox.recipe.odoo#68]
Hi folks,
I have a buildout for odoo 7.0, and when i use the latest recipe (at moment 1.9.1), it fails:

`Getting distribution for 'PIL'.
anybox.recipe.odoo.base: Could not find or install 'PIL'. You don't need to require it for OpenERP any more, since the recipe automatically adds a dependency to Pillow. If you really need it for other reasons, installing it system-wide is a good option.  Original exception zc.buildout.easy_install.MissingDistribution says: Couldn't find a distribution for 'PIL'.
While:
  Installing openerp.
Error: Couldn't find a distribution for 'PIL'.`

As you can see, in branch 7.0 [0] PIL is a requirement, not as in branch 8.0 [1] when the requirement is Pillow

Any suggestions are appreciated.
Thank you.

[0] https://github.com/odoo/odoo/blob/7.0/setup.py#L129
[1] https://github.com/odoo/odoo/blob/8.0/setup.py#L142

**Comment by petrus-v** [comment]
Hi!

Thanks for reporting, if you are using odoo v7.0 can you please use https://github.com/anybox/anybox.recipe.openerp?

regards

**Comment by ssaid** [comment]
Now is throwing another error: 

>   Requirement of openerp: python-dateutil<2
  Requirement of vobject: python-dateutil==2.4.0
While:
  Installing openerp.
Error: There is a version conflict.
We already have: python-dateutil 1.5
but vobject 0.9.0 requires 'python-dateutil==2.4.0'.

**Comment by petrus-v** [comment]
@ssaid,

Yes vobject 0.9.0 was released yesterday (https://pypi.python.org/pypi/vobject/0.9.0) we should use vobject < 0.9.0

**Comment by ssaid** [comment]
Petrus you are truly a life-saver! Thank you very much!!!
