### ISSUE TITLE
[BUG] empty log file

### ISSUE THREAD

**Issue by ventilooo** [anybox/anybox.recipe.odoo#91]
`./bin/upgrade_odoo --log-file=~/test.log --log-level=info --console-log-level=debug -d web`

The `test.log` is empty.

Is that normal ?

**Comment by petrus-v** [comment]
@ventilooo thanks for reporting issue.

We are mainly using the default value. It may have a bug! It appear to works with `anybox.recipe.openerp` (version 7 and earlier) but probably failed with anybox.recipe.odoo (odoo8 and after). Can you give us more information about the context? which odoo version are you using and which version of the `anybox.recipe.odoo` are you using?

**Comment by ventilooo** [comment]
context:
* odoo 9
* anybox.recipe.odoo-1.9.1-py2.7

NB: i'm working on a patch

**Comment by petrus-v** [comment]
@ventilooo 
At least upgrade logs are available on the odoo server file if one is set ``options.logfile = ${buildout:directory}/../log/odoo-server.log`
